# 是否显示刻度（外侧mtDNA环刻度）
show_ticks = yes
# 是否显示刻度标签
show_tick_labels = yes
<ticks>
# 刻度的半径，设置在外侧mtDNA蓝色环外缘
radius = 1.52r + 15p
# 刻度线的厚度
thickness = 3p
# 刻度线的方向，设置为向外
orientation = out
# 刻度线的颜色
color = black
# 刻度长度
size = 15p
# 标签的偏移量
label_offset = 5p
# 标签的格式，这里设置为显示整数
format = %d
<tick>
# 默认情况下不显示刻度
chromosomes_display_default = no
# 仅对线粒体染色体显示刻度
chromosomes = hsM
# 刻度的间隔，设置为1000bp
spacing = 1000
# 是否显示刻度标签
show_label = yes
# 标签的半径，设置在外侧mtDNA环外缘+60像素
label_radius = 1.52r + 60p
# 标签平行于弧线
label_parallel = yes
# 标签的大小
label_size = 20p
</tick>
</ticks>

