karyotype = karyotype.human.hg38.txt
chromosomes_display_default = no
chromosomes_units   = 0.1
chromosomes         = /hs([1-9]|1[0-9]|2[0-2]|[XYM])/
chromosomes_reverse = hsM
chromosomes_color = \
    hs1=chr_ring,hs2=chr_ring,hs3=chr_ring,hs4=chr_ring,hs5=chr_ring, \
    hs6=chr_ring,hs7=chr_ring,hs8=chr_ring,hs9=chr_ring,hs10=chr_ring, \
    hs11=chr_ring,hs12=chr_ring,hs13=chr_ring,hs14=chr_ring,hs15=chr_ring, \
    hs16=chr_ring,hs17=chr_ring,hs18=chr_ring,hs19=chr_ring,hs20=chr_ring, \
    hs21=chr_ring,hs22=chr_ring,hsX=chr_ring,hsY=chr_ring,hsM=mt_ring
chromosomes_radius = hsM:1r
chromosomes_scale  = hsM=0.5r
