BASE_DIR="/mnt/f/Onedrive/文档（科研）/脚本/Download/15-NUMTs-detector-V2/1-5-Vardetection"
PYTHON_DIR="${BASE_DIR}/python"

LIST_PATH="${BASE_DIR}/conf/list_path.txt"
PSL_TO_BED_PY="${PYTHON_DIR}/psl_to_numts_bed.py"
PYTHON_BIN="python3"
JOBS=8

PSL_SUFFIX="_all_regions.psl"
PSL_HUMAN_SUBDIR="pslHuman"
PSL_HUMAN_SUFFIX="_all_regions.human.psl"
BED_SUFFIX="_numts.bed"
