# Base paths
BASE_DIR="/mnt/f/Onedrive/文档（科研）/脚本/Download/15-NUMTs-detector-V2/1-5-Vardetection"
DATA_DIR="${BASE_DIR}/data"
PYTHON_DIR="${BASE_DIR}/python"
OUTPUT_BASE="${BASE_DIR}/output"
LIST_PATH="${BASE_DIR}/conf/list_path.txt"
JOBS=3
MIN_ACGT=1
LOGS_DIR="${OUTPUT_BASE}/logs"

# Reference files
REF_HUMAN="${DATA_DIR}/chrM_rCRS.fasta"
REF_CHIMP="${DATA_DIR}/chimpMT.fasta"
REF_HUMANCHIMP="${DATA_DIR}/Homo_sapiens.GRCh38.Pan_troglodytes.Pan_tro_3.0.dna.chromosome.MT.fa"

# Scripts
PSL_TO_BED_PY="${PYTHON_DIR}/psl_to_numts_bed.py"
FILTER_FASTA_PY="${PYTHON_DIR}/filter_fasta_nonempty.py"
PY_HUMAN="${PYTHON_DIR}/generateVariantTable.Human.py"
PY_HUMANCHIMP="${PYTHON_DIR}/generateVariantTable.HumanChimp.py"

#!CAP3, blat and clustalo need to be installed